#!/usr/bin/env bash

# Set window title
echo -ne "\033]0;Dev\007"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find \
        ~/Docker/flowerbox \
        ~/Docker/masterdata \
        ~/Docker/farmbox \
        ~/Docker/logibox \
        ~/Projects/Work/flowerbox \
        ~/Projects/Work/farmbox_ui \
        ~/Projects/Work/farmbox_api \
        ~/Projects/Work/logibox_ui \
        ~/Projects/Work/logibox_api \
        ~/Projects/Work/masterdata_api \
        ~/dotfiles \
        -mindepth 0 -maxdepth 0 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

# selected_name=$(basename "$selected" | tr . _)
selected_name=$(echo "$selected" | sed 's/\//-/g')
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
